#!/bin/bash
### BEGIN INIT INFO
# Provides: dxconfig
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Directory sample image configurator
### END INIT INFO
# This script configures Directory  based on available environment variables
# at boot time

case "$1" in

'start')
#
# import environment variables
#--------------------------------
for e in $(tr "\000" "\n" < /proc/1/environ); do
        eval "export $e"
done


source /opt/CA/Directory/dxserver/install/.dxprofile 

/opt/CA/Directory/dxserver/bin/dxserver start userdir_cadir
/opt/CA/Directory/dxserver/bin/dxserver start ssopolicy_cadir
/opt/CA/Directory/dxserver/bin/dxserver start ssosession_cadir
;;

'stop')

;;

esac
