#!/bin/sh
#
# Computer Associates
#
#__LINUX_INIT_INFO__
# chkconfig: 2345 99 01
# description: CA Siteminder service

### BEGIN INIT INFO
# Provides: psconfig
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Description: CA Siteminder
### END INIT INFO

# This script configures Policy Server based on available environment variables
# at boot time

case "$1" in

'start')
#
# import environment variables
#--------------------------------
for e in $(tr "\000" "\n" < /proc/1/environ); do
        eval "export $e"
done
source /opt/CA/siteminder/ca_ps_env.ksh

SM_POLICY_ADMIN_PASSWORD=${SM_POLICY_ADMIN_PASSWORD:="CAdemo123"}

while [ $(smldapsetup status -w${SM_POLICY_ADMIN_PASSWORD} -v | grep Success | wc -l) == 0 ]
do
   echo "Waiting for cadir to start" >> /tmp/psconfig
   sleep 5
done

#
# encrytpt the LDAP password with the PS key
#----------------------------------------------
smldapsetup reg -w${SM_POLICY_ADMIN_PASSWORD}
#
# set the superuser password
#------------------------------------
smreg -su siteminder
#
# setup the policy store (once only)
#--------------------------------------
if [ ! -f /opt/CA/sm-config/init-complete ]; then
   XPSDDInstall /opt/CA/siteminder/xps/dd/SmMaster.xdd
   XPSImport /opt/CA/siteminder/db/smpolicy.xml -npass
   touch /opt/CA/sm-config/init-complete
fi

#
# Register the adminUI
#------------------------
XPSRegClient siteminder:siteminder -adminui-setup -vT



#
# Restart policy server and adminUI
#-------------------------------------------
/opt/CA/siteminder/start-all
sleep 20

nohup /opt/CA/siteminder/adminui/bin/standalone.sh </dev/null >/dev/null 2>&1 &
;;


'stop')

;;

esac
