version: "3"
services:
  cadir:
    build:
      context: ./dockerfiles/cadir/14.1.00
    image: pconnor/dir:14.1.0
    hostname: cadir
    networks:
      - sm
    ports:
      - "15389:15389"
      - "5022:22"
    stdin_open: true
    tty: true
  casso:
    build:
      context: ./dockerfiles/siteminder/12.8/ps
    image: pconnor/sm-ps:12.8.5
    hostname: casso
    networks:
      - sm
    ports:
      - "2022:22"
      - "8443:8443"
      - "44441:44441"
      - "44442:44442"
      - "44443:44443"
      - "44444:44444"
    depends_on:
      - cadir
    stdin_open: true
    tty: true
  caag:
    build:
      context: ./dockerfiles/siteminder/12.8/ag
    image: pconnor/sm-ag:12.8.5
    hostname: caag
    ports:
      - "3022:22"
      - "9090:8080"
      - "9191:8181"
    depends_on:
        - casso
    stdin_open: true
    tty: true
    networks:
      - sm
networks:
  sm:
    name: sm-net
